The Scenario: The company database crashed, and the backup data is a mess. You must clean the "Orders" dataset.

In [16]:
import pandas as pd
df = pd.read_csv("ecommerce - ecommerce.csv")
print(df)

         id      customer name                        email purchase date  \
0       NaN      port beckwith    pbeckwith94@geocities.com   30 Jul 2025
1     689.0       kimmy haborn          khabornj4@google.es       pending
2     414.0   matthias calcutt      mcalcuttbh@freewebs.com    11/17/2025
3     789.0    ALGERNON NIAVES   aniaveslw@wunderground.com    2025-09-20
4       NaN  kynthia mcquirter  kmcquirter6s@yellowbook.com       unknown
...     ...                ...                          ...           ...
1095  467.0   ALLISTER MELLOWS         amellowscy@vimeo.com    2025-11-06
1096  122.0         carl lamey             clamey3d@php.net   17 Mar 2025
1097    NaN    CYMBRE COCKRILL       ccockrill8b@joomla.org   04 Jul 2025
1098    NaN      brynna petrie             bpetriec4@nhs.uk   15 Jul 2025
1099    NaN      tildy worlock        tworlocknw@disqus.com   10 Jan 2026

        price                                   trx shipping state
0     $460.25  548f8041-6317-4388-8dce-fe6de027505c      Argentina
1     $539.17                                   NaN         Panama
2     $534.17  4a22264d-4c87-4f9d-b4a5-99e343cb768e         Brazil
3     $345.84  83a9aa51-0a17-4fd8-a7c3-46a87c019f7b    Philippines
4     $283.29  29c1f562-82cb-40d1-97aa-a467feeb24d8      Indonesia
...       ...                                   ...            ...
1095  $127.81  7dac3d2e-cfce-423b-b34c-24c1efa35950            NaN
1096  $500.37  a900e75e-5035-4357-824e-d82f8db6a607        Armenia
1097  $482.79  98d998ca-0b37-4898-ae25-ab85c4d981db       Portugal
1098  $780.39  39d7652c-fe34-4e66-bf90-b5fb2cfbbf2f          China
1099  $173.04  6f79120f-5a4a-4de9-a201-481446647525      Indonesia

[1100 rows x 7 columns]

Handling Missing Data: The dataset is riddled with NaNs. You must use .dropna() to remove rows completely missing an Order ID, .fillna() to replace missing shipping states and transaction with "Unknown" that were lost during export.

In [17]:
df1 = df.dropna(subset=['id'])
df1

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,pending,$539.17,NaN,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,11/17/2025,$534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,2025-09-20,$345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,2025-12-30,$275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,unknown,$602.31,NaN,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,pending,$179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,unknown,$380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,NaN
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,pending,$699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,2025-11-06,$127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN
1096,122.0,carl lamey,clamey3d@php.net,17 Mar 2025,$500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

In [18]:
df2 = df1.copy()
fill_shippingand_transaction = df2[['shipping state','trx']].fillna('Unknown')
fill_shippingand_transaction

     shipping state                                   trx
1            Panama                               Unknown
2            Brazil  4a22264d-4c87-4f9d-b4a5-99e343cb768e
3       Philippines  83a9aa51-0a17-4fd8-a7c3-46a87c019f7b
5           Germany  f91b1691-2e28-486d-82eb-1a81cba02f98
6           Vietnam                               Unknown
...             ...                                   ...
1092          China  506a5235-eec5-493e-ab86-392840d8dd9b
1093        Unknown  0da184d0-4c09-4d6b-8d54-cc0f0980fa0e
1094           Peru  37d4d2d8-06e9-4304-aa87-cecb84d30a95
1095        Unknown  7dac3d2e-cfce-423b-b34c-24c1efa35950
1096        Armenia  a900e75e-5035-4357-824e-d82f8db6a607

[930 rows x 2 columns]

Handling Duplicates: A glitch caused users to be charged twice. You must use .duplicated() to find identical transactions and .drop_duplicates(keep='first') to refund/remove the errors.

In [19]:
df3 = df2.copy()
is_duplicated = df2.duplicated()
is_duplicated

1       False
2       False
3       False
5       False
6       False
        ...
1092    False
1093    False
1094    False
1095    False
1096    False
Length: 930, dtype: bool

In [20]:
df4 = df3.copy()
df_drop_first = df2.drop_duplicates(keep='first')
df_drop_first

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,pending,$539.17,NaN,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,11/17/2025,$534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,2025-09-20,$345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,2025-12-30,$275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,unknown,$602.31,NaN,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,pending,$179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,unknown,$380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,NaN
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,pending,$699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,2025-11-06,$127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN
1096,122.0,carl lamey,clamey3d@php.net,17 Mar 2025,$500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

"Price" is imported as a string (e.g., "$1,200.50"). You must remove the symbols and use pd.to_numeric() to turn it into a float.

In [21]:
df5 = df4.copy()
df5['price'] = df5['price'].astype(str).str.replace(r'[^\d.]', '', regex=True)
df5['price'] = pd.to_numeric(df5['price'], errors='coerce')
df5['price']

1       539.17
2       534.17
3       345.84
5       275.30
6       602.31
         ...
1092    179.86
1093    380.12
1094    699.39
1095    127.81
1096    500.37
Name: price, Length: 930, dtype: float64

Replace the “pending” and “unknown” with the previous datetime

In [22]:
df6 = df5.copy()
df6['purchase date'] = pd.to_datetime(df6['purchase date'], errors='coerce')
df6['purchase date'] = df6['purchase date'].ffill()
df6

C:\Users\USER\AppData\Local\Temp\ipykernel_22196\23223292.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df6['purchase date'] = pd.to_datetime(df6['purchase date'], errors='coerce')

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,NaT,539.17,NaN,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,2025-11-17,534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,2025-09-20,345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,2025-12-30,275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,2025-12-30,602.31,NaN,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,2025-06-07,179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,2025-06-07,380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,NaN
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,2025-06-07,699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,2025-11-06,127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN
1096,122.0,carl lamey,clamey3d@php.net,2025-03-17,500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

Convert “purchase date" from messy text into a proper datetime object using pd.to_datetime().

In [12]:
df7 = df6.copy()
df7['purchase date'] = pd.to_datetime(df7['purchase date'], errors='coerce', 
    format='mixed'
)
df7

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,NaT,539.17,NaN,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,2025-11-17,534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,2025-09-20,345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,2025-12-30,275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,2025-12-30,602.31,NaN,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,2025-06-07,179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,2025-06-07,380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,NaN
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,2025-06-07,699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,2025-11-06,127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN
1096,122.0,carl lamey,clamey3d@php.net,2025-03-17,500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

Convert the “purchase date" format from various format into this format “M/D/Y”

In [13]:
df8 = df7.copy()
df8['purchase date'] = pd.to_datetime(df8['purchase date'], errors='coerce')
df8['purchase date'] = df8['purchase date'].dt.strftime('%m/%d/%Y')
df8

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,NaN,539.17,NaN,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,11/17/2025,534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,09/20/2025,345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,12/30/2025,275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,12/30/2025,602.31,NaN,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,06/07/2025,179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,06/07/2025,380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,NaN
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,06/07/2025,699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,11/06/2025,127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN
1096,122.0,carl lamey,clamey3d@php.net,03/17/2025,500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

String Manipulation: The "Names" column has chaotic capitalization and extra spaces. You use .str.title() and .str.strip() to fix this. You must also extract the email domain (e.g., extracting "gmail.com" from "user@gmail.com") using .str.split().

In [14]:
df9 = df8.copy()
df9['customer name'] = df9['customer name'].str.strip().str.title()
df9

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,Kimmy Haborn,khabornj4@google.es,NaN,539.17,NaN,Panama
2,414.0,Matthias Calcutt,mcalcuttbh@freewebs.com,11/17/2025,534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,Algernon Niaves,aniaveslw@wunderground.com,09/20/2025,345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,Hayes Kleewein,hkleeweinl3@kickstarter.com,12/30/2025,275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,Susanne Cummins,scummins2o@paypal.com,12/30/2025,602.31,NaN,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,Shawn Hengoed,shengoedo7@ustream.tv,06/07/2025,179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,Maridel Rogeron,mrogeron2f@google.de,06/07/2025,380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,NaN
1094,331.0,Britteny Euesden,beuesden96@mayoclinic.com,06/07/2025,699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,Allister Mellows,amellowscy@vimeo.com,11/06/2025,127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN
1096,122.0,Carl Lamey,clamey3d@php.net,03/17/2025,500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

In [15]:
df10 = df9.copy()
df10['domain'] = df10['email'].str.split('@').str[1]
df10

,id,customer name,email,purchase date,price,trx,shipping state,domain
1,689.0,Kimmy Haborn,khabornj4@google.es,NaN,539.17,NaN,Panama,google.es
2,414.0,Matthias Calcutt,mcalcuttbh@freewebs.com,11/17/2025,534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil,freewebs.com
3,789.0,Algernon Niaves,aniaveslw@wunderground.com,09/20/2025,345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines,wunderground.com
5,760.0,Hayes Kleewein,hkleeweinl3@kickstarter.com,12/30/2025,275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany,kickstarter.com
6,97.0,Susanne Cummins,scummins2o@paypal.com,12/30/2025,602.31,NaN,Vietnam,paypal.com
...,...,...,...,...,...,...,...,...
1092,872.0,Shawn Hengoed,shengoedo7@ustream.tv,06/07/2025,179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China,ustream.tv
1093,88.0,Maridel Rogeron,mrogeron2f@google.de,06/07/2025,380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,NaN,google.de
1094,331.0,Britteny Euesden,beuesden96@mayoclinic.com,06/07/2025,699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru,mayoclinic.com
1095,467.0,Allister Mellows,amellowscy@vimeo.com,11/06/2025,127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN,vimeo.com
1096,122.0,Carl Lamey,clamey3d@php.net,03/17/2025,500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia,php.net